plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

// Add this to specify the main class in the manifest
jar {
    manifest {
        attributes(
                'Main-Class': 'org.example.Main' // Replace with your main class's fully qualified name
        )
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}